### ISSUE TITLE
react-native chrono - Invalid RegExp: Quantifier has nothing to repeat, js engine: hermes

### ISSUE THREAD

**Issue by sajjad-karimi** [wanasit/chrono#483] opened 2022-12-05 09:55 UTC
I've used **chrono-node** in **react-native** app and when I import chrono-node in app with hermes engine . I get the following error:

`SyntaxError: Invalid RegExp: Quantifier has nothing to repeat, js engine: hermes`

**Comment by wanasit** [comment] 2022-12-25 05:06
Hello @sajjad-karimi sorry for my slow reply. I'm not aware of the Hermes engine. 

Will try to see if we can support that engine.

**Comment by sanjeev-karat** [comment] 2022-12-26 12:45
We have a similar issue too. Do we have any workaround/suggestions?

**Comment by Slapbox** [comment] 2023-01-18 23:34
@wanasit the issue is related to this one: hermes/issues/696

I tried using the `core-js` [polyfill](https://github.com/zloirock/core-js#regexp-named-capture-groups): `core-js/proposals/regexp-named-groups` - but then it just throws with `Invalid RegExp: Invalid escape`

The issue specifically is due to the use of named capture groups in the ZH and RU locale files, but I've not found any way to remedy the issue so far.

**Comment by Slapbox** [comment] 2023-01-19 00:17
Confirmed that commenting out the RU and ZH parsers from the `dist/index.js` resolves my issue.

**Comment by Slapbox** [comment] 2023-02-24 00:51
Should be fixed in future versions of Hermes if the "completed" status of this issue is anything to go by: https://github.com/facebook/hermes/issues/696

**Comment by wanasit** [comment] 2023-03-18 04:13
Yes. I have checked out the latest build for the Hermes engine and it compiles the RegExp correctly now. This should make its way to react native app soon.

**Comment by mfbx9da4** [comment] 2023-10-31 10:28
I tried commenting out ZH and RU and adding the core-js polyfill and my error turned into:

```
Maximum call stack size exceeded
    at module.exports (/.../node_modules/core-js/internals/is-regexp.js:12:9)
```

**Comment by wanasit** [comment] 2023-11-19 05:25
As replied in #527. Please try update to Chrono v2.7.3
https://github.com/wanasit/chrono/releases/tag/v2.7.3

I have fixed the issue by switching to lazy-loading/creating RegEx patterns. In the longer term, we can only wait for Hermes Engine to support those patterns.

I'm closing this issue. Please comment on #527 or create a new issue for Hermes engine.

**Closed by wanasit** 2023-11-19 05:25 UTC
Labels: wont-fix / rejected
